### ISSUE TITLE
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

### ISSUE THREAD

**Issue by yesitsjess** [hart-lab/bagel#14]
Hi, I'm using build 113 and able to generate BFs with no issue:
```
  bagel/BAGEL.py bf -i $fc -o "bagel_final_20200205/bf_${org}_CEGv2_NEGv1.tsv" -e bagel/CEGv2.txt -n bagel/NEGv1.txt -c $i
  bagel/BAGEL.py pr -i "bagel_final_20200205/bf_${org}_CEGv2_NEGv1.tsv" -o "bagel_final_20200205/pr_${org}_CEGv2_NEGv1.tsv" -e bagel/CEGv2.txt -n bagel/NEGv1.txt
```
But when I pass the BF file to the PR function I get the following error:
```
Traceback (most recent call last):
  File "bagel/BAGEL.py", line 1064, in <module>
    bagel()
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bagel/BAGEL.py", line 1056, in calculate_precision_recall
    fout.write('{0:s}\t{1:4.3f}\t{2:4.3f}\t{3:4.3f}\n'.format(g, bf.iloc[g, bf_column], recall, precision))
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/pandas/core/indexing.py", line 2143, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/software/virtualenv/python2.7/64/otp_7/lib/python2.7/site-packages/pandas/core/indexing.py", line 227, in _has_valid_tuple
    .format(types=self._valid_types))
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types
```
Any advice?

**Comment by vaofford** [comment]
Hullo,

We also seem to be getting the same/similar error with our Docker container with build 113:

```
Traceback (most recent call last):
  File "/opt/wsi-t113/python3/pandas/core/indexing.py", line 223, in _has_valid_tuple
    self._validate_key(k, i)
  File "/opt/wsi-t113/python3/pandas/core/indexing.py", line 2084, in _validate_key
    "a [{types}]".format(types=self._valid_types))
ValueError: Can only index by location with a [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/wsi-t113/bin/BAGEL.py", line 1064, in <module>
    bagel()
  File "/opt/wsi-t113/python3/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/wsi-t113/python3/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/wsi-t113/python3/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/wsi-t113/python3/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/wsi-t113/python3/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/wsi-t113/bin/BAGEL.py", line 1056, in calculate_precision_recall
    fout.write('{0:s}\t{1:4.3f}\t{2:4.3f}\t{3:4.3f}\n'.format(g, bf.iloc[g, bf_column], recall, precision))
  File "/opt/wsi-t113/python3/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/wsi-t113/python3/pandas/core/indexing.py", line 2143, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/opt/wsi-t113/python3/pandas/core/indexing.py", line 227, in _has_valid_tuple
    .format(types=self._valid_types))
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types
```
Happy to share the container if it helps to replicate the error.  We do get the output file with a header, but the error seems to prevent it generating any other values:

`Gene	BF	Recall	Precision`

Thanks in advance!

Victoria

**Comment by mkiritsy** [comment]
Running into the same issue. If anyone seems to have figured out a work around or might be able to help, please let me know! Thanks in advance, Mike

**Comment by rooeikim** [comment]
Hi, sorry for late response.
I've updated BAGEL to fix the bug. 
bf.iloc[g, bf_column] -> bf.loc[g, bf_column]
